initial Crowd Helm Chart based on Confluence Helm Chart
atlassian-labs/data-center-helm-charts pull request #106
Opened 2021-04-15 11:46 UTC by LouisZschaler

This crowd chart was created based on the confluence chart.
Please let me know if any additional efforts are required.

2021-04-16 00:37 UTC, gjacobsatl commented
Thanks for the contribution - I just noticed when diffing this against the current Confluence charts that the recent PRs haven't been included.
Mainly https://github.com/atlassian-labs/data-center-helm-charts/pull/98 which switched the nfs-permission-fixer and https://github.com/atlassian-labs/data-center-helm-charts/pull/102 though I'm guessing all of them since whenever this was originally created. Can we get those included?

2021-04-16 05:47 UTC, pathob commented
Thanks @gjacobsatl and yeah, we were a bit slow. We will add the latest features of the other charts.

2021-04-19 16:46 UTC, LouisZschaler commented
I adopted relevant changes from #98 and #102.

Any idea why the CLA is still pending?

2021-04-22 04:00 UTC, pathob commented
Hi @nanux and @gjacobsatl 

There is definetly something wrong with your CLA bot. After new commits are pushed here, the CLA check is failing again. Only after I tried to resubmit it and got the following error message, the CLA check succeeded again.

![image](https://user-images.githubusercontent.com/4580157/115653635-189d0c00-a362-11eb-8bbb-1a4f86cc0293.png)

But now it looks like we already need a rebase again...

2021-04-22 04:19 UTC, nanux commented
> Hi @nanux and @gjacobsatl
> 
> There is definetly something wrong with your CLA bot. After new commits are pushed here, the CLA check is failing again. Only after I tried to resubmit it and got the following error message, the CLA check succeeded again.
> 
> ![image](https://user-images.githubusercontent.com/4580157/115653635-189d0c00-a362-11eb-8bbb-1a4f86cc0293.png)
> 
> But now it looks like we already need a rebase again...

Thank you for the report - did you fill the agreement on https://cla-external.services.atlassian.com/cla?

2021-04-22 06:24 UTC, pathob commented
> > Hi @nanux and @gjacobsatl
> > There is definetly something wrong with your CLA bot. After new commits are pushed here, the CLA check is failing again. Only after I tried to resubmit it and got the following error message, the CLA check succeeded again.
> > ![image](https://user-images.githubusercontent.com/4580157/115653635-189d0c00-a362-11eb-8bbb-1a4f86cc0293.png)
> > But now it looks like we already need a rebase again...
> 
> Thank you for the report - did you fill the agreement on https://cla-external.services.atlassian.com/cla?

Yes :)

2021-04-22 07:35 UTC, LouisZschaler commented
Rebase performed and CLA resigned.

2021-04-22 23:51 UTC, gorakong commented
@pathob that's because the CLA was signed with an incorrect email address. It's looking for llzschaler@aservo.com (with 2 L's in the front), whilst it was signed with lzschaler@aservo.com.

2021-04-23 00:00 UTC, gorakong commented
I can go ahead and fix the record for you. In the meantime, to unblock yourself, you can go ahead and merge the PR.

2021-04-23 07:33 UTC, pathob commented
@gorakong

> @pathob that's because the CLA was signed with an incorrect email address. It's looking for [llzschaler@aservo.com](mailto:llzschaler@aservo.com) (with 2 L's in the front), whilst it was signed with [lzschaler@aservo.com](mailto:lzschaler@aservo.com).

Oh

> I can go ahead and fix the record for you.

Thank you!

> In the meantime, to unblock yourself, you can go ahead and merge the PR.

How do you mean that? We cannot do the merge as we are not part of Atlassian. And it looks like we somehow need a strategy to get this merged, We are now out-of-date with the base branch for the third time this week...

2021-04-23 20:16 UTC, gorakong commented
@pathob np! sorry, what i meant was the maintainers should feel free to merge the PR when they're ready 😄

2021-04-27 11:55 UTC, pathob commented
Hi @nanux and @gjacobsatl

can we please try again? Branch is up to date again, and CLA check successful. :smiley:

2021-05-04 02:17 UTC, pathob commented
Hi @nanux and @gjacobsatl

sorry, I really don't want to annoy you, but the longer this PR is open, the more it will diverge again from the other charts. Is this PR ready to get merged?

2021-05-04 11:04 UTC, nanux requested changes
Thank you for the Crowd chart! Sorry, it took longer, we had to consider potential implications to the scope of the project. Crowd wasn't originally planned to be included in the first version of officially supported helm charts. But I don't want your contribution to be lost. For now, we are still planning to provide official helm chart support for Jira, Bitbucket and Confluence in the first milestone. But the nature of the helm chart repo allows us to collocated charts that are officially supported and in alpha testing if we provide enough notice to the users to distinguish the level of support.

I will follow up your PR with the disclaimer for the Crowd chart and also some other `values.yaml` files for quicker testing so we can set up CI on our side. Overall the PR looks good, just a few comments:

Can you please include the application version so we are consistent with other products?

Can you also share what scenarios and use cases you tested with the helm chart? I have tested some basic functionality and one issue I have noticed is that the JDBC connection parameters are not picked up in the setup - see my comment.

2021-05-06 08:45 UTC, nanux commented
Sorry, could you please merge `master` to branch so we can run the Github Actions here (I've updated them so they can run on PR)?

@pathob @LouisZschaler could you please also have a look at the questions above? I wonder if you had success with database configuration.

I would like to merge the PR soon so it doesn't diverge from `master` too much.

2021-05-10 07:57 UTC, pathob commented
Hi @nanux , thanks for your review and sorry for the small delay now from our site.

We are fine with the missing official support that you also mentioned in the linked ticket. For us it is currently more important to also have a Crowd chart that does not diverge too much from the others and that we may be able to make future contributions to.

We will add the app version and rebase to the latest master soon.

And yes, you got us. We also noticed now that the Crowd Docker image does not provide the environment variables to set the database so the database section does not work at all. And we are also not 100% sure about the other features of the Charts as we couldn't test all of them.

For now we will remove the database section again. Users can still use the web interface to setup the database - and we btw. are doing it by creating a Crowd config file using an init container. That's why we didn't notice.

2021-05-10 09:46 UTC, LouisZschaler commented on src/main/charts/crowd/Chart.yaml
> +appVersion:
done

2021-05-10 09:51 UTC, LouisZschaler commented on src/main/charts/crowd/values.yaml
> +  type:
That is correct. The Docker image doesn't provide the necessary endpoint. Should that ever change, the values and the db connectivity test could be part of this chart again.
We use additional init containers with an initial db dump to jump the setup.

2021-05-12 07:09 UTC, nanux commented
@pathob thank you very much. Please let me know if you get around to implement the changes. If not, I can merge this and change it on our side.

2021-05-12 07:43 UTC, LouisZschaler commented
Sorry, I missed to adjust the README.md, deleting the database values. Now it's actually clean.

I would recommend to merge it like this, and see if the Crowd Docker Image will have the database endpoint eventually. Our specialized solutions should not be part of a clean Crowd helm chart.

2021-05-13 00:58 UTC, nanux approved these changes

2021-05-13 00:58 UTC, nanux commented
Thanks @pathob and @LouisZschaler for pushing through with this change.

2021-05-13 00:59 UTC, merged