DCKUBE-332: Update the minimal supported kubernetes version v1.19
atlassian-labs/data-center-helm-charts pull request #154
Opened 2021-05-28 06:42 UTC by nanux

1.19 is the oldest supported version of kubernetes. The cloud providers are still allowing to install older versions but I think we should try to stay in the supported window. From 1.19 the supported window is one year.

The main changes required are related to Ingress entity changes:

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

2021-05-28 06:59 UTC, yzha645 approved these changes

2021-05-31 04:18 UTC, tarka approved these changes

2021-05-31 04:26 UTC, nghazali approved these changes

2021-05-31 04:48 UTC, errcode1202 approved these changes

2021-05-31 05:36 UTC, errcode1202 requested changes
We still reference `1.17` in parts of the documentation i.e.
https://github.com/atlassian-labs/data-center-helm-charts/blob/master/docs/PREREQUISITES.md
 need to make sure that there are no other `1.17` references.

2021-05-31 09:20 UTC, nanux commented
> We still reference `1.17` in parts of the documentation i.e.
> https://github.com/atlassian-labs/data-center-helm-charts/blob/master/docs/PREREQUISITES.md
> need to make sure that there are no other `1.17` references.

I think this is updated on https://github.com/atlassian-labs/data-center-helm-charts/pull/154/files#diff-3de916a26bbdad10a9d8707fb66eaa9ce8ce1d86f7e8f0f0674342511ec34f23 - I've run fulltext search and didn't find more 1.17 references. I have also updated the `README.md` files in the chart folders as they are auto-generated with a scritp.

2021-05-31 22:25 UTC, errcode1202 commented
> > We still reference `1.17` in parts of the documentation i.e.
> > https://github.com/atlassian-labs/data-center-helm-charts/blob/master/docs/PREREQUISITES.md
> > need to make sure that there are no other `1.17` references.
> 
> I think this is updated on https://github.com/atlassian-labs/data-center-helm-charts/pull/154/files#diff-3de916a26bbdad10a9d8707fb66eaa9ce8ce1d86f7e8f0f0674342511ec34f23 - I've run fulltext search and didn't find more 1.17 references. I have also updated the `README.md` files in the chart folders as they are auto-generated with a script.

You did update these references. Ignore me :)

2021-05-31 22:26 UTC, errcode1202 approved these changes

2021-05-31 22:40 UTC, merged