DCKUBE-349: Convert documentation to mkdocs
atlassian-labs/data-center-helm-charts pull request #220
Opened 2021-07-29 03:18 UTC by nanux

* Convert all documentation to mkdocs format https://www.mkdocs.org/
* Use Material theme for mkdocs https://squidfunk.github.io/mkdocs-material/
* Mark external links with an icon
* Use Atlassian colours for background and dark theme
* Remove links in the footer of the page as there is a full navigation experience
* Link the documentation from the README.md file in Github
* Added favicon and logos
* Move copyright to footer
* Add announcement banner on top with Beta warning and link for feedback
* In same places converted content to tabs (e.g. for product variants)
* Add Github action to deploy the documentation with every change in `main/master` branch
* Minify the output for the final site

2021-07-29 03:27 UTC, nanux commented on .github/workflows/documentation.yaml
> +      - main
Getting ready for the `main` branch rename

2021-07-29 03:27 UTC, nanux commented on .github/workflows/documentation.yaml
> +        run: mkdocs gh-deploy --force
This will deploy into `gh-pages` branch and that is then deployed by Github Pages

2021-07-29 03:27 UTC, nanux commented on README.md
> +We provide [extensive documentation](https://atlassian-labs.github.io/data-center-helm-charts/) to support our Helm charts. This includes prerequisites, set up, installation, examples, and more.
This is the new entrypoint for documentation from Github, users shouldn't browse the documentation on Github.

2021-07-29 03:27 UTC, nanux commented on docs/docs/.pages
> +nav:
This is a way how to reorder how the pages are displayed in the navigation.

It is using awesome pages plugin - https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#customize-navigation

2021-07-29 03:27 UTC, nanux commented on docs/docs/README.md
> +!!! warning
This is an example of Admonition

https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage

2021-07-29 03:27 UTC, nanux commented on docs/docs/README.md
> +This project contains [Helm charts](https://helm.sh/){.external} for installing Atlassian's [Jira Data Center](https://www.atlassian.com/enterprise/data-center/jira){.external}, [Confluence Data Cent
If the link is external, I've appended `{.external}` class to it so it will display a small icon signifying that link goes outside of the docs.

2021-07-29 03:27 UTC, nanux commented on docs/docs/examples/cluster/CLOUD_PROVIDERS.md
> -***
These links are not necessary as we have navigation provided by mkdocs now. They are removed from all the pages.

2021-07-29 03:27 UTC, nanux commented on docs/docs/examples/database/AMAZON_RDS.md
> +=== "Jira"
Example of tabbed content. This is very useful when we have product variants.

https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#usage

2021-07-29 03:27 UTC, nanux commented on docs/docs/examples/elasticsearch/BITBUCKET_ELASTICSEARCH.md
> +```yaml
Making sure we have appropriate syntax highlighting.

2021-07-29 03:27 UTC, nanux commented on docs/docs/operations/product_upgrades/CONFLUENCE_UPGRADE.md
> +# Confluence rolling upgrade
I believe the recommendation is sentence casing for headlines.

2021-07-29 03:27 UTC, nanux commented on docs/mkdocs.yml
> +    - search.highlight
Enabling search

2021-07-29 03:27 UTC, nanux commented on docs/overrides/main.html
> +  The helm charts are in Beta, <a href="https://community.atlassian.com/t5/Atlassian-Data-Center-on/gh-p/DC_Kubernetes" class="atl-bright-color">share your feedback</a>.
Announcement banner displayed on every page.

2021-07-29 03:27 UTC, nanux commented on docs/mkdocs.yml
> +copyright: Copyright &copy; [2021] Atlassian and others.
Copyright has moved to the footer for each page.

2021-07-29 03:27 UTC, nanux commented on docs/mkdocs.yml
> +    - icon: fontawesome/brands/atlassian
Icon in the right corner of the footer linking to community.

2021-07-30 04:00 UTC, tan-ro approved these changes

2021-08-02 02:04 UTC, errcode1202 requested changes

2021-08-02 02:04 UTC, errcode1202 commented on DEVELOPMENT.md
> +To make the work with the documentation easy, there is a `Makefile` in the project root folder. To start the server just run:
This sentence is a bit off, reads better like this:

> To make working with the documentation easier, there is a .....

2021-08-02 02:44 UTC, nanux commented
Also added Google Analytics tracking ID

2021-08-02 04:25 UTC, tan-ro approved these changes

2021-08-02 06:31 UTC, merged