Add supported boundaries
atlassian-labs/data-center-helm-charts pull request #236
Opened 2021-08-11 23:22 UTC by tan-ro

2021-08-13 02:17 UTC, nanux commented
@tan-ro is this containing all the planned changes?

2021-08-13 02:22 UTC, tan-ro commented
No, I've been working on it locally

2021-08-17 00:42 UTC, nanux commented
Pushed updated filename to fix navigation.

It was throwing:
```
mkdocs_awesome_pages_plugin.navigation.NavEntryNotFound: Nav entry "SUPPORT_BOUNDARIES.md" not found. [/Users/abrokes/code/data-center-helm-charts/docs/docs/troubleshooting/.pages]
```

2021-08-17 00:49 UTC, nanux commented
I've also added https://github.com/atlassian-labs/data-center-helm-charts/pull/236/commits/0e29bb837f16d25536e807c44ea56fd807c1d354 to prevent this in future.

2021-08-18 00:33 UTC, errcode1202 requested changes

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/README.md
> +If you find any issue, [raise a ticket](https://github.com/atlassian-labs/data-center-helm-charts/issues/new){.external}. If you have general feedback or question regarding the charts, use [Atlassian
Should this be:

`If you find any issues,` (plural)

also 

`or questions regarding` (plural)

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +You are responsible for creating the components that are required by the product for your type of deployment, as describes in the [Prerequisites](../userguide/PREREQUISITES.md). You need to insert th
The words:
`for your type of deployment, as describes`

should be:

`for your type of deployment, as described` 

replace `describes` with `described`

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +If you find any issue, [raise a ticket](https://github.com/atlassian-labs/data-center-helm-charts/issues/new){.external}. If you have general feedback or questions regarding the charts, use [Atlassia
pluralise `issue`?

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +There is a set of required components that you can create in multiple ways. You are responsible for creating them correctly so you can use them in the Helm charts.
Can we add a link to these components à la the prerequisites

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +Helm charts need to be installed in the existing Kubernetes cluster. You need to make sure that you have enough privileges to run the application and create all the necessary entities that the Helm c
Just wondering if the first sentence is required? i.e. `Helm charts need to be installed in the existing Kubernetes cluster.`

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +Kubernetes setup requires you to have shared storage if you want to have a clustered instance. It's completely up to you how you set up the shared storage. The main requirement is that this storage n
can hyperlink `shared storage` to our shared storage section in the configuration guide

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +Thereis a large number of combinations and potential setup scenarios and we can't support all of them. Our Helm charts expect you to provide a persistent volume claim or a similar accessible shared s
Typo `Thereis`

2021-08-18 00:33 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +* Istio infrastructure
Can we hyperlink `Istio` to the official page

2021-08-18 00:35 UTC, errcode1202 commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +## Not supported configurations
Might be better to rename this section: `Unsupported configurations`

2021-08-19 05:35 UTC, errcode1202 approved these changes

2021-08-19 05:36 UTC, merged

2021-08-19 05:37 UTC, tan-ro commented on docs/docs/troubleshooting/SUPPORT_BOUNDARIES.md
> +    * Due to several reasons, Istio is imposing networking rules on every workload in the Kubernetes cluster that doesn’t work with our deployments.
I missed that one. I'll fix it in the next PR