DCKUBE-580 Add some content for DEVELOPMENT.md document
atlassian-labs/data-center-helm-charts pull request #255
Opened 2021-08-22 23:54 UTC by nghazali

2021-08-23 22:43 UTC, errcode1202 requested changes

2021-08-23 22:43 UTC, errcode1202 commented on DEVELOPMENT.md
> +## Build and test the project
Im really not sure if we should be advertising this stuff. `helm_install.sh` is something **we use only for CI**, and isnt used for "development" of the charts per se. It's caused problems/confusion in the past and Ive stopped using it myself. To be honest if a turn key solution is what we're trying to provide here then we should wait for the official Terraform scripts.

2021-08-23 22:43 UTC, errcode1202 commented on DEVELOPMENT.md
> +
A lot of this content feels like its duplicated from the PREREQUISITE doc Would it not be better to add this detail to it and then reference it from here?

2021-08-23 22:46 UTC, errcode1202 requested changes

2021-08-23 22:46 UTC, errcode1202 commented on DEVELOPMENT.md
> +
Im really not sure if we should be advertising this stuff. helm_install.sh is something we use only for CI, and isnt used for "development" of the charts per se. It's caused problems/confusion in the past and Ive stopped using it myself. To be honest if a turn key solution is what we're trying to provide here then we should wait for the official Terraform scripts.

2021-08-24 00:18 UTC, nghazali commented
As result of the team discussion I am closing this PR.

2021-08-24 00:19 UTC, closed without merging