Update the BB and Conf image names, as the -server suffix is now deprecated
atlassian-labs/data-center-helm-charts pull request #259
Opened 2021-08-23 04:49 UTC by tarka

2021-08-23 04:49 UTC, badgersow approved these changes

2021-08-23 04:56 UTC, nanux commented
@tarka, this will need a change to the expected outcome test - https://github.com/atlassian-labs/data-center-helm-charts/pull/259/checks?check_run_id=3396854349

2021-08-23 04:57 UTC, nanux requested changes
@tarka, this will need a change to the expected outcome test - https://github.com/atlassian-labs/data-center-helm-charts/pull/259/checks?check_run_id=3396854349

2021-08-24 00:24 UTC, nanux commented
Now you will need to rebase on `main` as there was a bump of the Confluence version to 7.13.0 🍀

2021-08-24 04:40 UTC, nanux approved these changes

2021-08-24 04:41 UTC, merged