feat(perms): Paramterize setPermissions boolean flag
atlassian-labs/data-center-helm-charts pull request #97
Opened 2021-04-04 15:50 UTC by sylus

2021-04-06 16:30 UTC, pbruski approved these changes

2021-04-07 01:39 UTC, nanux requested changes

2021-04-07 01:39 UTC, nanux commented on src/main/charts/confluence/values.yaml
> +  # Boolean flag on whether to set permissions in the Confluence container.
`# -- Boolean to define whether to set home directory permissions on startup of Confluence container. Set to false to disable this behaviour.`

2021-04-28 07:43 UTC, nanux approved these changes

2021-04-28 08:10 UTC, merged